name = "taskify-mvp"
compatibility_date = "2024-01-01"
pages_build_output_dir = "build"

[env.development]
name = "taskify-mvp-dev"

[env.staging]
name = "taskify-mvp-staging"

[env.production]
name = "taskify-mvp-prod"

# Database configuration
[[env.development.d1_databases]]
binding = "DB"
database_name = "taskify-dev"
database_id = "dev-database-id"
preview_database_id = "dev-preview-database-id"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "taskify-staging"
database_id = "staging-database-id"

[[env.production.d1_databases]]
binding = "DB"
database_name = "taskify-prod"
database_id = "production-database-id"

# KV configuration
[[env.development.kv_namespaces]]
binding = "KV"
id = "dev-kv-namespace-id"
preview_id = "dev-kv-preview-id"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "staging-kv-namespace-id"

[[env.production.kv_namespaces]]
binding = "KV"
id = "production-kv-namespace-id"

# Analytics and monitoring
[env.production.analytics_engine_datasets]
binding = "ANALYTICS"
dataset = "taskify-analytics"

# Environment variables
[env.development.vars]
ENVIRONMENT = "development"
API_BASE_URL = "http://localhost:5173"
LOG_LEVEL = "debug"

[env.staging.vars]
ENVIRONMENT = "staging"
API_BASE_URL = "https://taskify-staging.pages.dev"
LOG_LEVEL = "info"

[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://taskify.pages.dev"
LOG_LEVEL = "warn"
